### PR TITLE
Fix event handlers to trigger only once per second

### LINKED ISSUE #26: Crackle during audio playback
This can sometimes happen in the middle of normal playback, but it's difficult to reproduce reliably. I think it happens when the system / browser is under load from other processes / pages.

But I can reproduce it fairly consistently (in Chrome on Linux) using the following steps:

1. Open the examples, e.g. https://dschoon.github.io/react-waves/
2. Open Chrome's DevTools
3. Open device toolbar (mobile icon in the top-left of devtools)
4. **Switch speed from "Online" to "Low-tier mobile"**
5. Play the first track (Africa)
6. Now grab the page with your mouse and wiggle it up and down rapidly. **I can hear crackle from the audio playback!**
7. (Switch back to "Online" mode otherwise the next page reload will take forever.)

PR coming soon...

### PR DESCRIPTION
**Pull request by joeytwiddle**
Closes #26

I think the intent of this code was to call `onPosChange` only once per second.

But while `currentTime` has been converted into a whole number, `this.props.pos` was still fractional! So the comparison was always failing, and the callback was always being called.

This was causing too much work in JavaScript, and producing audible crackle on some devices.

So I fixed the comparison to trigger only once per second, as originally intended.

- I put both the `ceil()` calls on the same line, to make it clearer that we are comparing two integers.

### CODE REVIEW

File: src/components/Waveform/index.js [hunk 1]
```diff
@@ -102,9 +101,8 @@ export default class Waveform extends React.Component {
 
     registerEvent(this._wavesurfer, EVENT.SEEK, pos => {
       let duration = this._wavesurfer.getDuration();
-      let currentTime = Math.ceil(duration*pos);
 
-      if (currentTime !== this.props.pos) {
+      if (Math.ceil(duration * pos) !== Math.ceil(this.props.pos)) {
```
Comment (joeytwiddle) [inline src/components/Waveform/index.js:105]: Do we even need a comparison here? Seeks should be pretty rare events anyway.
